KayanIntern/Models/ErrorViewModel.cs
namespace KayanIntern.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KayanIntern/Controllers/Base/AuthorizationController.cs
using KayanIntern.Provider.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace KayanIntern.KayanIntern.Controllers.Base
{
    public class AuthorizationController : Controller
    {
        protected Users CurrentUser { get; set; }

        public AuthorizationController()
        {
            CurrentUser = new Users();
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var cookie = context.HttpContext.User;

            var currentusertype = CurrentUser.GetType();

            foreach (var property in currentusertype.GetProperties())
            {
                var cookieclaim = cookie.FindFirst(property.Name);
                if (cookieclaim != null)
                {
                    var propertytype = property.PropertyType;
                    var cookieClaimValue = cookieclaim.Value;

                    if (propertytype == typeof(string))
                    {
                        property.SetValue(CurrentUser, cookieClaimValue);
                    }
                }
            }



            //CurrentUser.UserName = cookie.FindFirst(ClaimTypes.Name)?.Value; // use ?.value to get the claim value
            //CurrentUser.Email = cookie.FindFirst(ClaimTypes.Email)?.Value;
            //CurrentUser.Role = cookie.FindFirst(ClaimTypes.Role)?.Value;

            base.OnActionExecuting(context);
        }



        //public void OnActionExecuted(ActionExecutedContext context)
        //{
        //    // Code to be executed after the action method
        //}
    }
}

KayanIntern/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KayanIntern.KayanIntern.Controllers.Base
{
    [Authorize]
    public class DashboardController : AuthorizationController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }
    }
}

KayanIntern/Controllers/HomeController.cs
using KayanIntern.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KayanIntern.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KayanIntern/Controllers/LoginController.cs
using KayanIntern.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace KayanIntern.Controllers;

public class LoginController : Controller
{
    private readonly Repository.IUser.IUsers _User;

    public LoginController(Repository.IUser.IUsers user)
    {
        _User = user;
    }

    public IActionResult Index()
    {
        ClaimsPrincipal claimUser = HttpContext.User;

        if (claimUser.Identity.IsAuthenticated)
            return RedirectToAction("Index", "Dashboard");

        return View(new LoginVM { Email = "" });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(LoginVM loginVM)
    {
        var user = _User.Login(loginVM);

        if (user == null)
        {
            ModelState.AddModelError(String.Empty, "The Email or Password are incorrect");
            return View(new LoginVM { Email = "" });
        }
        else
        {
            var rememberMe = loginVM.RememberMe;
            List<Claim> claims = new List<Claim>() {
                    new Claim("Email", user.Email.ToString(), ClaimValueTypes.String),
                    new Claim("FirstName", user.FirstName.ToString(),ClaimValueTypes.String),
                    new Claim("LastName", user.LastName.ToString(), ClaimValueTypes.String),
                    new Claim("Birthday", user.Birthday.ToString(), ClaimValueTypes.String)

                };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties
            {
                AllowRefresh = true,
                IsPersistent = rememberMe
            };

            if (rememberMe)
            {
                properties.ExpiresUtc = DateTime.UtcNow.AddDays(3);
            }
            else
            {
                properties.IsPersistent = false;

            }

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity), properties);
            return RedirectToAction("Index", "Dashboard");
        }

    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

        return RedirectToAction("Index", "Login");
    }
}

KayanIntern/Controllers/RegistrationController.cs
using KayanIntern.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace KayanIntern.KayanIntern.Controllers
{

    public class RegistrationController : Controller
    {
        private readonly Repository.IUser.IUsers _User;

        public RegistrationController(Repository.IUser.IUsers user)
        {
            _User = user;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(string email, string password, string firstName, string lastName, DateTime birthday)
        {
            RegistrationVM registrationVM = new RegistrationVM();
            registrationVM.Email = email;
            registrationVM.Password = password;
            registrationVM.FirstName = firstName;
            registrationVM.LastName = lastName;
            registrationVM.Birthday = birthday;

            var user = _User.SignUp(registrationVM);


            if (user == null)
            {
                return RedirectToAction("Privacy", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");

            };
        }

    }
}

KayanIntern/Views/Dashboard/Index.cshtml
@model KayanIntern.ViewModels.DashboardVM
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_DashboardLayout";
    var FirstName = User.FindFirst("FirstName")?.Value;
}
<h3>Welcome @FirstName!</h3>

KayanIntern/Views/Dashboard/Profile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Profile";
    Layout = "_DashboardLayout";
}

KayanIntern/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<header class="header-2">
    <div class="page-header min-vh-75 relative"
         style="background-image: url('./assets/img/city-profile.jpg')">
        <span class="mask"></span>
        <div class="container">
            <div class="row">
                <div class="col-lg-7 text-center mx-auto">
                    <h1 class="text-light pt-3 mt-n5">KayanIntern</h1>
                    <p class="lead text-light mt-3">
                        Revolutionizing Intern Training and Development <br />
                        Cultivating Talent, Nurturing Success.
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

KayanIntern/Views/Login/Index.cshtml
@model KayanIntern.ViewModels.LoginVM

@{
    ViewData["Title"] = "Login";
}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card blur blur-shadow z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-3 mx-3 z-index-2" style="border-radius: 0.5rem;">
                    <div class="bg-gradient-primary shadow-dark border-radius-lg py-3 pe-1">
                        <h4 class="text-light font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form asp-controller="Login" asp-action="Index" method="post" class="text-start">
                        <div class="input-group input-group-outline my-3">
                            <label class="form-label">Email</label>
                            <input type="email" asp-for="Email" class="form-control">
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <label class="form-label">Password</label>
                            <input type="password" asp-for="Password" class="form-control">
                        </div>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-check form-switch d-flex align-items-center mb-3">
                            <input class="form-check-input" type="checkbox" id="rememberMe" name="RememberMe">
                            <label class="form-check-label mb-0 ms-3" for="rememberMe">Remember me</label>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2">Sign in</button>
                        </div>

                        <p class="mt-4 text-sm text-center">
                            Don't have an account?
                            <a asp-controller="Registration" asp-action="Index" class="text-primary text-gradient font-weight-bold">Sign up</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

KayanIntern/Views/Login/Login.cshtml
@model KayanIntern.ViewModels.LoginVM

@{ViewData["Title"] = "Login";}

<div class="container mt-4">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form asp-controller="Login" asp-action="Login" method="post" class="text-start">
                        <div class="input-group input-group-outline my-3">
                            <label class="form-label">Email</label>
                            <input type="email" asp-for="Email" class="form-control">
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <label class="form-label">Password</label>
                            <input type="password" asp-for="Password" class="form-control">
                        </div>
                        <div class="form-check form-switch d-flex align-items-center mb-3">
                            <input class="form-check-input" type="checkbox" id="rememberMe" checked>
                            <label class="form-check-label mb-0 ms-3" for="rememberMe">Remember me</label>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Sign in</button>
                        </div>
                        <p class="mt-4 text-sm text-center">
                            Don't have an account?
                            <a href="../pages/sign-up.html" class="text-primary text-gradient font-weight-bold">Sign up</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@* <script>
    var inputs = document.querySelectorAll('input');

    for (var i = 0; i < inputs.length; i++) {
        inputs[i].addEventListener('focus', function (e) {
            this.parentElement.classList.add('is-focused');
        }, false);

        inputs[i].onkeyup = function (e) {
            if (this.value != "") {
                this.parentElement.classList.add('is-filled');
            } else {
                this.parentElement.classList.remove('is-filled');
            }
        };

        inputs[i].addEventListener('focusout', function (e) {
            if (this.value != "") {
                this.parentElement.classList.add('is-filled');
            }
            this.parentElement.classList.remove('is-focused');
        }, false);
    }
</script> *@

KayanIntern/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - KayanIntern</title>
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/favicon.ico">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link id="pagestyle" href="~/assets/css/material-dashboard.css" rel="stylesheet" />
</head>

<body class="g-sidenav-show bg-gray-200">
    <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" href="#" target="_blank">
                
                    <img src="~/img/KI logo 75x75.png" class="navbar-brand-img h-100" alt="main_logo">
                    <span class="ms-1 font-weight-bold text-white">KayanIntern</span>
                
            </a>
        </div>
        <hr class="horizontal light mt-0 mb-2">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active bg-gradient-primary text-white" asp-action="Index" asp-controller="Dashboard">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">dashboard</i>
                        </div>
                        <span class="nav-link-text ms-1">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white " asp-action="Profile" asp-controller="Dashboard">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">account_circle</i>
                        </div>
                        <span class="nav-link-text ms-1">Profile</span>
                    </a>
                </li>
            </ul>
        </div>
    </aside>
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
                        <li class="breadcrumb-item text-sm text-dark active" aria-current="page">@ViewData["Title"]</li>
                    </ol>
                    <h6 class="font-weight-bolder mb-0">@ViewData["Title"]</h6>
                </nav>
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                        <div class="input-group input-group-outline">
                            <label class="form-label">Type here...</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <ul class="navbar-nav  justify-content-end">
                        <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item px-3 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-body p-0">
                                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
                            </a>
                        </li>
                        <li class="nav-item dropdown pe-2 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-bell cursor-pointer"></i>
                            </a>
                            <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                              
                            </ul>
                        </li>
                        <li class="nav-item d-flex align-items-center">
                            <a asp-action="Logout" asp-controller="Login" class="nav-link text-body font-weight-bold px-0">
                                <i class="fa fa-user me-sm-1"></i>
                                <span class="d-sm-inline d-none">Sign out</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="mx-3">@RenderBody()</div>
    </main>
    <div class="fixed-plugin">
        <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
            <i class="material-icons py-2">settings</i>
        </a>
        <div class="card shadow-lg">
            <div class="card-header pb-0 pt-3">
                <div class="float-start">
                    <h5 class="mt-3 mb-0">Customize your theme</h5>
                    <p>See our dashboard options.</p>
                </div>
                <div class="float-end mt-4">
                    <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                        <i class="material-icons">clear</i>
                    </button>
                </div>
                <!-- End Toggle Button -->
            </div>
            <hr class="horizontal dark my-1">
            <div class="card-body pt-sm-3 pt-0">
                <!-- Sidebar Backgrounds -->
                <div>
                    <h6 class="mb-0">Sidebar Colors</h6>
                </div>
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors my-2 text-start">
                        <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                    </div>
                </a>
                <!-- Sidenav Type -->
                <div class="mt-3">
                    <h6 class="mb-0">Sidenav Type</h6>
                    <p class="text-sm">Choose between 2 different sidenav types.</p>
                </div>
                <div class="d-flex">
                    <button class="btn bg-gradient-dark px-3 mb-2 active" data-class="bg-gradient-dark" onclick="sidebarType(this)">Dark</button>
                    <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
                    <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
                </div>
                <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
                <!-- Navbar Fixed -->
                <div class="mt-3 d-flex">
                    <h6 class="mb-0">Navbar Fixed</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
                    </div>
                </div>
                <hr class="horizontal dark my-3">
                <div class="mt-2 d-flex">
                    <h6 class="mb-0">Light / Dark</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
                    </div>
                </div>
                <hr class="horizontal dark my-sm-4">
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/chartjs.min.js"></script>
    <script src="~/js/site.js"></script> 
    <script src="~/assests/js/material-dashboard.js"></script>
    <script src="~/assets/js/material-dashboard.min.js"></script>
</body>

</html>

KayanIntern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KayanIntern</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KayanIntern.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/c4bce5b816.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <script src="~/js/material-dashboard.js"></script>
    <script src="~/assets/js/plugins/flatpickr.min.js"></script>
</head>

<body class="bg-gray-200">
    <div class="container position-sticky z-index-sticky top-0">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
                    <div class="container-fluid ps-2 pe-0">
                        <img src="~/img/KI logo 75x75.png" class="mx-2 img-fluid" alt="" style="width: 25px; height: auto;" />
                        <a class="navbar-brand ms-lg-0 ms-3 text-light" asp-controller="Home" asp-action="Index">
                            KayanIntern
                        </a>
                        <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon mt-2">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </span>
                        </button>
                        <div class="collapse navbar-collapse" id="navigation">
                            <ul class="navbar-nav mx-auto">
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center me-2 text-light" aria-current="page" href="#">
                                        <i class="fa fa-person-chalkboard opacity-6 text-light me-1"></i>
                                        Training Programs
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2 text-light" asp-action="Index" asp-controller="Dashboard">
                                        <i class="fa fa-chart-pie opacity-6 text-light me-1"></i>
                                        Dashboard
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2 text-light" href="#">
                                        <i class="fas fa-users opacity-6 text-light me-1"></i>
                                        Internships
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2 text-light" href="#">
                                        <i class="fa-regular fa-circle-question opacity-6 text-light me-1"></i>
                                        FAQ
                                    </a>
                                </li>
                            </ul>
                            @if (ViewData["Title"] != "Login")
                            {
                                <ul class="navbar-nav d-lg-flex d-none">
                                    <li class="nav-item d-flex align-items-center">
                                        <a class="btn btn-primary btn-sm mb-0 me-2" target="_blank" asp-controller="Login" asp-action="Index">Sign In</a>
                                    </li>
                                </ul>
                            }
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

    <main class="main-content  mt-0">
        <div class="page-header align-items-start min-vh-100" style="background-image: url('https://img2.wallspic.com/crops/6/8/2/5/7/175286/175286-ecoregion-natural_environment-mountain-biome-slope-1920x1080.jpg');">
            <span class="mask bg-gradient-dark opacity-6"></span>
            <div class="container skip-navbar">
                <main role="main" class="pb-3 mb-4">
                    @RenderBody()
                </main>
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/material-dashboard.js"></script>
    <script src="~/js/material-dashboard.min.js"></script>
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>
    <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/js/plugins/smooth-scrollbar.min.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="~/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/js/plugins/countup.min.js"></script>
    <script src="~/js/site.js" type="text/javascript"></script>
</body>
</html>